workflow: compliance: Use additional compliance checks
Adds the compliance checks that are being used in sdk-nrf

Signed-off-by: Jamie McCrae <jamie.mccrae@nordicsemi.no>

diff --git a/.github/workflows/compliance.yml b/.github/workflows/compliance.yml
--- a/.github/workflows/compliance.yml
+++ b/.github/workflows/compliance.yml
@@ -84,14 +84,14 @@ jobs:
       working-directory: nrf-bm
       if: contains(github.event.pull_request.user.login, 'dependabot[bot]') != true
       run: |
-        export PATH="$HOME/.local/bin:$PATH"
-        export PATH="$HOME/bin:$PATH"
         export ZEPHYR_BASE="$(dirname "$(pwd)")/zephyr"
         # debug
         ls -la
         git log --pretty=oneline | head -n 10
         exec 2> compliance_errors.txt
-        $ZEPHYR_BASE/scripts/ci/check_compliance.py -m Codeowners -m Devicetree -m Identity -m Nits -m Gitlint -m pylint -c origin/${BASE_REF}..
+        $ZEPHYR_BASE/scripts/ci/check_compliance.py --annotate \
+        -e KconfigBasicNoModules -e ClangFormat -e SysbuildKconfigBasicNoModules \
+        -c origin/${BASE_REF}..
         if [[ $? -ne 0 ]]; then
           echo "$?" >&2
         fi
@@ -103,31 +103,30 @@ jobs:
       with:
         name: compliance.xml
         path: nrf-bm/compliance.xml
+        overwrite: true
 
     - name: check-warns
       working-directory: nrf-bm
+      if: contains(github.event.pull_request.user.login, 'dependabot[bot]') != true
       run: |
-        if [[ -s 'compliance_errors.txt' ]]; then
-         echo "ERRORS FOUND! Exiting"
-         echo "$(<compliance_errors.txt )"
-         exit 1;
+        export ZEPHYR_BASE="$(dirname "$(pwd)")/zephyr"
+        if [[ ! -s "compliance.xml" ]]; then
+          exit 1;
         fi
 
-    - name: check-warns
-      working-directory: nrf-bm
-      run: |
-        for file in Codeowners.txt Devicetree.txt Gitlint.txt Identity.txt Nits.txt pylint.txt
-        do
-          if [[ -s $file ]]; then
-            errors=$(cat $file)
+        files=($($ZEPHYR_BASE/scripts/ci/check_compliance.py -l))
+        for file in "${files[@]}"; do
+          f="${file}.txt"
+          if [[ -s $f ]]; then
+            errors=$(cat $f)
             errors="${errors//'%'/'%25'}"
             errors="${errors//$'\n'/'%0A'}"
             errors="${errors//$'\r'/'%0D'}"
-            echo "::error file=${file}::$errors"
+            echo "::error file=${f}::$errors"
             exit=1
           fi
         done
 
-        if [[ $exit == 1 ]]; then
-          exit 1
+        if [ "${exit}" == "1" ]; then
+          exit 1;
         fi
